version: '3' # latest version of docker composer

services: # All container service lists
  flask:
    build: ./Flask
    ports: 
    - 5000:5000
    environment: 
            PORT: 5000
            FLASK_DEBUG: 1

  mongodb: # container name
    image: mongo # image name and version
    ports:
    - 27017:27017 # Host:Container
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express: # container name
    image: mongo-express 
    ports: # image name and version
    - 8081:8081 # Host:Container
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password