version: '3'

services:
  mongodb:
    container_name: MongoDB
    image: mongo
    hostname: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongo-networks
    volumes:
      - mongo-data:/data/db

  mongo-express:
    container_name: MongoExpress
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    networks:
      - mongo-networks

networks:
  mongo-networks:
    driver: bridge
  volumes:
    mongo-data:
		  driver: local
